name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "any"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: ESLint
        run: npm run lint
